<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Damage Report Export</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #222;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .header h2 {
            margin: 0;
            color: #0b3d91;
            font-size: 20px;
        }

        .header p {
            margin: 4px 0;
            font-size: 12px;
        }

        .meta {
            margin-bottom: 15px;
        }

        .meta p {
            margin: 3px 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th, td {
            border: 1px solid #333;
            padding: 8px;
            text-align: left;
            vertical-align: top;
        }

        th {
            background: #0b3d91;
            color: white;
        }

        tr:nth-child(even) {
            background: #f4f6f8;
        }

        .footer {
            margin-top: 20px;
            font-size: 11px;
            text-align: right;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>TESDA Damage Report History</h2>
        <p>Automated Tools and Equipment Inventory Control System</p>
    </div>

    <div class="meta">
        <p><strong>Search:</strong> {{ $search ?: 'None' }}</p>
        <p><strong>Date Generated:</strong> {{ $generatedAt }}</p>
        <p><strong>Total Records:</strong> {{ $damageReports->count() }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Damage ID</th>
                <th>Serial #</th>
                <th>Item</th>
                <th>Observation</th>
                <th>Borrower Name</th>
                <th>Date Reported</th>
            </tr>
        </thead>
        <tbody>
            @forelse($damageReports as $report)
                <tr>
                    <td>{{ $report->damage_id }}</td>
                    <td>{{ $report->serial_no }}</td>
                    <td>{{ $report->item_name ?? '-' }}</td>
                    <td>{{ $report->observation ?? '-' }}</td>
                    <td>{{ $report->borrower_name ?? '-' }}</td>
                    <td>
                        {{ $report->reported_at ? \Carbon\Carbon::parse($report->reported_at)->format('F d, Y h:i A') : '-' }}
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" style="text-align:center;">No damage reports found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by TESDA Inventory System
    </div>
</body>
</html>