<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>
        {{ $status === 'Damaged' ? 'Damaged Items Export' : 'Inventory Export' }}
    </title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #222;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .header h2 {
            margin: 0;
            color: #0b3d91;
            font-size: 20px;
        }

        .header p {
            margin: 4px 0;
            font-size: 12px;
        }

        .meta {
            margin-bottom: 15px;
        }

        .meta p {
            margin: 3px 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th, td {
            border: 1px solid #333;
            padding: 8px;
            text-align: left;
            vertical-align: top;
        }

        th {
            background: #0b3d91;
            color: white;
            font-size: 12px;
        }

        tr:nth-child(even) {
            background: #f4f6f8;
        }

        .footer {
            margin-top: 20px;
            font-size: 11px;
            text-align: right;
        }

        .status {
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>
            {{ $status === 'Damaged' ? 'TESDA Damaged Items Report' : 'TESDA Inventory Report' }}
        </h2>
        <p>Automated Tools and Equipment Inventory Control System</p>
    </div>

    <div class="meta">
        <p><strong>Filter:</strong> {{ $status }}</p>
        <p><strong>Date Generated:</strong> {{ $generatedAt }}</p>
        <p><strong>Total Records:</strong> {{ $items->count() }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Serial #</th>
                <th>Item</th>
                <th>Description</th>
                <th>Source of Fund</th>
                <th>Classification</th>
                <th>Date Acquired</th>

                @if($status === 'Damaged')
                    <th>Observation</th>
                    <th>Reported At</th>
                @endif

                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($items as $item)
                <tr>
                    <td>{{ $item->serial_no }}</td>
                    <td>{{ $item->item_name }}</td>
                    <td>{{ $item->description ?? '-' }}</td>
                    <td>{{ $item->source_of_fund ?? '-' }}</td>
                    <td>{{ $item->classification ?? '-' }}</td>
                    <td>
                        {{ $item->date_acquired ? \Carbon\Carbon::parse($item->date_acquired)->format('F d, Y') : '-' }}
                    </td>

                    @if($status === 'Damaged')
                        <td>{{ $item->observation ?? '-' }}</td>
                        <td>
                            {{ $item->reported_at ? \Carbon\Carbon::parse($item->reported_at)->format('F d, Y') : '-' }}
                        </td>
                    @endif

                    <td class="status">{{ $item->status }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="{{ $status === 'Damaged' ? 9 : 7 }}" style="text-align:center;">
                        No inventory records found.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by TESDA Inventory System
    </div>
</body>
</html>