<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Maintenance Report Export</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #222;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .header h2 {
            margin: 0;
            color: #0b3d91;
            font-size: 20px;
        }

        .header p {
            margin: 4px 0;
            font-size: 12px;
        }

        .meta {
            margin-bottom: 15px;
        }

        .meta p {
            margin: 3px 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th, td {
            border: 1px solid #333;
            padding: 8px;
            text-align: left;
            vertical-align: top;
        }

        th {
            background: #0b3d91;
            color: white;
            font-size: 12px;
        }

        tr:nth-child(even) {
            background: #f4f6f8;
        }

        .footer {
            margin-top: 20px;
            font-size: 11px;
            text-align: right;
        }

        .money {
            text-align: right;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>TESDA Maintenance Report</h2>
        <p>Automated Tools and Equipment Inventory Control System</p>
    </div>

    <div class="meta">
        <p><strong>Date Generated:</strong> {{ $generatedAt }}</p>
        <p><strong>Total Records:</strong> {{ $records->count() }}</p>
        <p><strong>Items Under Repair:</strong> {{ $maintenanceCounts['total'] ?? 0 }}</p>
        <p><strong>Complete Repairs:</strong> {{ $maintenanceCounts['complete_repairs'] ?? 0 }}</p>
        <p><strong>Unserviceable:</strong> {{ $maintenanceCounts['unserviceable'] ?? 0 }}</p>
        <p><strong>Total Repair Cost:</strong> ₱{{ number_format($maintenanceCounts['total_repair_cost'] ?? 0, 2) }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Serial #</th>
                <th>Item</th>
                <th>Issue / Problem</th>
                <th>Date Reported</th>
                <th>Repair Cost</th>
                <th>Expected Completion</th>
                <th>Remarks</th>
            </tr>
        </thead>
        <tbody>
            @forelse($records as $record)
                <tr>
                    <td>{{ $record->serial_no }}</td>
                    <td>{{ $record->item_name ?? '-' }}</td>
                    <td>{{ $record->observation ?? '-' }}</td>
                    <td>
                        {{ $record->date_reported ? \Carbon\Carbon::parse($record->date_reported)->format('F d, Y') : '-' }}
                    </td>
                    <td class="money">
                        {{ $record->repair_cost ? '₱' . number_format($record->repair_cost, 2) : '-' }}
                    </td>
                    <td>
                        {{ $record->expected_completion ? \Carbon\Carbon::parse($record->expected_completion)->format('F d, Y') : '-' }}
                    </td>
                    <td>{{ $record->remarks ?? '-' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align:center;">No maintenance records found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by TESDA Inventory System
    </div>
</body>
</html>